# Generated by Django 6.0.4 on 2026-04-15 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('system_type', models.CharField(choices=[('openmrs', 'OpenMRS'), ('ugandaemr', 'UgandaEMR'), ('dhis2', 'DHIS2'), ('custom', 'Custom FHIR Server')], max_length=16)),
                ('base_url', models.URLField(help_text='Base URL of the external EMR or FHIR server')),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('hmac_secret', models.CharField(blank=True, default='', help_text='Pre-shared HMAC key for signing integration requests', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_direction', models.CharField(choices=[('push', 'Push Only'), ('pull', 'Pull Only'), ('both', 'Bidirectional')], default='both', max_length=8)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='core.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SyncChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('model_name', models.CharField(help_text='Django model that was changed', max_length=64)),
                ('object_id', models.CharField(max_length=64)),
                ('change_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=8)),
                ('payload', models.JSONField(default=dict)),
                ('client_timestamp', models.DateTimeField(help_text='Timestamp from the client device')),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('conflict_resolved', models.BooleanField(default=False)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_changes', to='accounts.device')),
            ],
            options={
                'ordering': ['-client_timestamp'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='integration_model_n_208766_idx'), models.Index(fields=['device', 'is_synced'], name='integration_device__934a90_idx')],
            },
        ),
    ]
