# Generated by Django 6.0.4 on 2026-04-15 19:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Ministry of Health facility code', max_length=64, unique=True)),
                ('address', models.TextField(blank=True, default='')),
                ('district', models.CharField(blank=True, default='', max_length=128)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('facility_type', models.CharField(choices=[('hc2', 'Health Centre II'), ('hc3', 'Health Centre III'), ('hc4', 'Health Centre IV'), ('hospital', 'Hospital'), ('rrh', 'Regional Referral Hospital'), ('nrh', 'National Referral Hospital'), ('private', 'Private Clinic')], default='hc3', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'ordering': ['name'],
            },
        ),
    ]
