# Generated by Django 6.0.4 on 2026-04-15 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('encounter_type', models.CharField(choices=[('outpatient', 'Outpatient Visit'), ('inpatient', 'Inpatient Admission'), ('emergency', 'Emergency Visit'), ('referral', 'Referral'), ('lab_only', 'Lab Visit Only'), ('pharmacy', 'Pharmacy Visit'), ('anc', 'Antenatal Care'), ('immunization', 'Immunization'), ('chronic_review', 'Chronic Care Review')], default='outpatient', max_length=32)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='in_progress', max_length=16)),
                ('chief_complaint', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('diagnosis_codes', models.JSONField(blank=True, default=list, help_text='List of ICD-10 codes')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='core.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='accounts.patient')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='accounts.provider')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('test_name', models.CharField(max_length=255)),
                ('test_code', models.CharField(blank=True, default='', help_text='LOINC code', max_length=32)),
                ('result_value', models.CharField(blank=True, default='', max_length=255)),
                ('result_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('reference_range', models.CharField(blank=True, default='', max_length=64)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('result_file_uri', models.URLField(blank=True, default='', help_text='Link to PDF or image of the result')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preliminary', 'Preliminary'), ('final', 'Final'), ('amended', 'Amended')], default='final', max_length=16)),
                ('recorded_at', models.DateTimeField()),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='records.encounter')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_labs', to='accounts.provider')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(blank=True, default='', max_length=255)),
                ('dose', models.CharField(max_length=64)),
                ('dose_unit', models.CharField(blank=True, default='', max_length=32)),
                ('frequency', models.CharField(help_text='Dosing frequency, for example: twice daily', max_length=64)),
                ('route', models.CharField(blank=True, default='oral', max_length=32)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('prescriber_notes', models.TextField(blank=True, default='')),
                ('is_dispensed', models.BooleanField(default=False)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='records.encounter')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('observation_type', models.CharField(help_text='Category: vital_sign, symptom, finding, social_history', max_length=64)),
                ('code', models.CharField(help_text='LOINC or local code for the observation', max_length=32)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('value_text', models.TextField(blank=True, default='')),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('reference_range', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('preliminary', 'Preliminary'), ('final', 'Final'), ('amended', 'Amended'), ('cancelled', 'Cancelled')], default='final', max_length=16)),
                ('recorded_at', models.DateTimeField()),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='records.encounter')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', 'start_time'], name='records_enc_patient_a17d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['facility', 'start_time'], name='records_enc_facilit_a4d3eb_idx'),
        ),
    ]
