# Generated by Django 6.0.4 on 2026-04-15 19:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('document_type', models.CharField(choices=[('lab_report', 'Lab Report'), ('prescription', 'Prescription'), ('discharge_summary', 'Discharge Summary'), ('referral_letter', 'Referral Letter'), ('imaging', 'Imaging / Radiology'), ('insurance_card', 'Insurance Card'), ('immunization', 'Immunization Record'), ('consent_form', 'Consent Form'), ('other', 'Other')], default='other', max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('mime_type', models.CharField(default='application/pdf', max_length=64)),
                ('file', models.FileField(upload_to='patient_documents/%Y/%m/')),
                ('file_uri', models.URLField(blank=True, default='', help_text='External URI if stored in S3')),
                ('file_hash', models.CharField(help_text='SHA-256 hash for deduplication', max_length=64, unique=True)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by a health worker')),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='records.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to='accounts.provider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
