# Generated by Django 6.0.4 on 2026-04-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('patient', 'Patient'), ('provider', 'Provider'), ('facility_admin', 'Facility Admin'), ('system', 'System'), ('integration', 'Integration Adapter')], max_length=16)),
                ('actor_id', models.PositiveBigIntegerField(help_text='User ID of the actor')),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('share', 'Share via QR'), ('consent_grant', 'Consent Granted'), ('consent_revoke', 'Consent Revoked'), ('export', 'Data Export'), ('sync', 'Sync Event')], max_length=16)),
                ('target_type', models.CharField(help_text='Model name of the resource accessed', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'managed': True,
                'indexes': [models.Index(fields=['actor_type', 'actor_id'], name='audit_audit_actor_t_8bde50_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__2d648a_idx'), models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx')],
            },
        ),
    ]
