# Generated by Django 6.0.4 on 2026-04-15 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('patients_enrolled', models.PositiveIntegerField(default=0)),
                ('encounters_created', models.PositiveIntegerField(default=0)),
                ('documents_uploaded', models.PositiveIntegerField(default=0)),
                ('qr_shares_generated', models.PositiveIntegerField(default=0)),
                ('qr_shares_redeemed', models.PositiveIntegerField(default=0)),
                ('successful_syncs', models.PositiveIntegerField(default=0)),
                ('failed_syncs', models.PositiveIntegerField(default=0)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='core.facility')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'facility')},
            },
        ),
    ]
